language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y make
  - sudo apt-get install -y g++
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libfontconfig1-dev
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y libxrender-dev
  - sudo apt-get install -y libasound2-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y cmake
  - sudo apt-get install -y liblua5.2-dev
  - sudo apt-get install -y cppcheck
  - sudo apt-get install -y git

before_script:
  - git clone https://github.com/sphair/ClanLib.git
  - cd ClanLib
  - git checkout 3.0-stable
  - ./autogen.sh
  - ./configure
  - make --silent
  - sudo make install --silent

script:
  - cmake .
  - make -j4
  - cppcheck --quiet --error-exitcode=1 --force --enable=all .
